import type { PaletteColor } from "@/lib/color-analysis";

export type SeasonPreset = {
  key: string;
  season: string;
  family: "spring" | "summer" | "autumn" | "winter";
  temperature: string;
  value: string;
  chroma: string;
  contrast: string;
  mood: string;
  appBackground: string;
  appInk: string;
  palette: PaletteColor[];
  neutrals: string[];
  accents: string[];
  avoid: string[];
};

export const seasonPresets: SeasonPreset[] = [
  {
    key: "light-spring",
    season: "Light Spring",
    family: "spring",
    temperature: "warm-neutral",
    value: "light",
    chroma: "clear but gentle",
    contrast: "low to medium",
    mood: "fresh peach, cream, warm daylight",
    appBackground: "#F7EBDD",
    appInk: "#4D382A",
    palette: [
      { name: "Peach Milk", hex: "#F2C7AA", use: "blouses and soft knits" },
      { name: "Warm Ivory", hex: "#FFF1D8", use: "base layers" },
      { name: "Apricot", hex: "#F4A56F", use: "cheeks and lips" },
      { name: "Light Aqua", hex: "#9AD8D2", use: "fresh accents" },
      { name: "Honey Beige", hex: "#DDBB76", use: "warm neutral pieces" },
    ],
    neutrals: ["warm ivory", "cream", "honey beige", "light camel"],
    accents: ["peach", "apricot", "light aqua", "warm mint"],
    avoid: ["black", "dusty mauve", "charcoal", "blue-gray"],
  },
  {
    key: "warm-spring",
    season: "Warm Spring",
    family: "spring",
    temperature: "warm",
    value: "light to medium",
    chroma: "clear",
    contrast: "medium",
    mood: "golden, lively, sunlit",
    appBackground: "#F4E6CE",
    appInk: "#56351F",
    palette: [
      { name: "Golden Cream", hex: "#FFE7A8", use: "tops near the face" },
      { name: "Coral Peach", hex: "#F58B70", use: "lip and blush focus" },
      { name: "Warm Poppy", hex: "#EA5E45", use: "statement accents" },
      { name: "Fresh Leaf", hex: "#8DBA5A", use: "shirts and dresses" },
      { name: "Camel", hex: "#C58C4A", use: "outerwear and bags" },
    ],
    neutrals: ["cream", "camel", "warm beige", "light warm brown"],
    accents: ["coral", "poppy", "fresh leaf", "turquoise"],
    avoid: ["cool gray", "icy pink", "burgundy", "muted dusty tones"],
  },
  {
    key: "bright-spring",
    season: "Bright Spring",
    family: "spring",
    temperature: "warm-neutral",
    value: "light to medium",
    chroma: "bright / clear",
    contrast: "medium to high",
    mood: "clear, playful, glassy",
    appBackground: "#F7E9D2",
    appInk: "#442D24",
    palette: [
      { name: "Clear Coral", hex: "#FF6F61", use: "statement tops" },
      { name: "Butter Yellow", hex: "#FFD86B", use: "fresh highlights" },
      { name: "Bright Aqua", hex: "#35BFC0", use: "clean accents" },
      { name: "Leaf Green", hex: "#66B447", use: "spring color blocking" },
      { name: "Warm Cocoa", hex: "#7A4A32", use: "grounding neutral" },
    ],
    neutrals: ["cream", "warm cocoa", "clear navy", "camel"],
    accents: ["coral", "aqua", "butter yellow", "leaf green"],
    avoid: ["muddy olive", "dusty rose", "ash gray", "muted taupe"],
  },
  {
    key: "light-summer",
    season: "Light Summer",
    family: "summer",
    temperature: "cool-neutral",
    value: "light",
    chroma: "soft-clear",
    contrast: "low",
    mood: "powder, mist, clean linen",
    appBackground: "#EEF0EA",
    appInk: "#39404A",
    palette: [
      { name: "Powder Pink", hex: "#EBC6CE", use: "tops and blush" },
      { name: "Lavender Mist", hex: "#C9C3E6", use: "soft accents" },
      { name: "Sky Blue", hex: "#B7D4E8", use: "shirts and knits" },
      { name: "Seafoam", hex: "#BFD9D1", use: "light layers" },
      { name: "Dove Gray", hex: "#BFC4C8", use: "neutral tailoring" },
    ],
    neutrals: ["dove gray", "soft white", "cool beige", "light navy"],
    accents: ["powder pink", "lavender", "sky blue", "seafoam"],
    avoid: ["orange", "mustard", "black", "heavy olive"],
  },
  {
    key: "cool-summer",
    season: "Cool Summer",
    family: "summer",
    temperature: "cool",
    value: "light to medium",
    chroma: "soft",
    contrast: "medium",
    mood: "rose, slate, quiet clarity",
    appBackground: "#ECECEA",
    appInk: "#343A45",
    palette: [
      { name: "Rose Pink", hex: "#D89AAA", use: "lip and blouse color" },
      { name: "Blue Gray", hex: "#8FA8BC", use: "outerwear" },
      { name: "Cool Mauve", hex: "#B99CB2", use: "makeup harmony" },
      { name: "Soft Navy", hex: "#57687D", use: "deep neutral" },
      { name: "Cloud Gray", hex: "#D7D8D6", use: "base pieces" },
    ],
    neutrals: ["cloud gray", "soft navy", "rose beige", "cool taupe"],
    accents: ["rose", "mauve", "blue gray", "plum"],
    avoid: ["camel", "tomato red", "golden yellow", "orange brown"],
  },
  {
    key: "soft-summer",
    season: "Soft Summer",
    family: "summer",
    temperature: "cool-neutral",
    value: "light to medium",
    chroma: "muted / smoky",
    contrast: "low to medium",
    mood: "mauve, sage-gray, watercolor softness",
    appBackground: "#EEECE5",
    appInk: "#3D4245",
    palette: [
      { name: "Dusty Rose", hex: "#C8A2A8", use: "tops and lips" },
      { name: "Mauve Taupe", hex: "#A9969C", use: "wardrobe base" },
      { name: "Sage Gray", hex: "#A7B0A2", use: "knits and shirting" },
      { name: "Soft Slate", hex: "#7F91A0", use: "denim and outerwear" },
      { name: "Mushroom", hex: "#BDB5AD", use: "neutral tailoring" },
    ],
    neutrals: ["mushroom", "cool taupe", "dove gray", "soft navy"],
    accents: ["dusty rose", "sage gray", "soft slate", "muted berry"],
    avoid: ["bright yellow", "orange", "clear coral", "black-white contrast"],
  },
  {
    key: "soft-autumn",
    season: "Soft Autumn",
    family: "autumn",
    temperature: "warm-neutral",
    value: "medium",
    chroma: "muted / earthy",
    contrast: "low to medium",
    mood: "sesame, clay, tea, softened earth",
    appBackground: "#EEE1D0",
    appInk: "#46362C",
    palette: [
      { name: "Sesame", hex: "#D7C19D", use: "base layers" },
      { name: "Clay Rose", hex: "#BF8B78", use: "lips and tops" },
      { name: "Moss", hex: "#8E9674", use: "knits and jackets" },
      { name: "Warm Taupe", hex: "#9B806A", use: "tailoring" },
      { name: "Cocoa", hex: "#6C5445", use: "bags and shoes" },
    ],
    neutrals: ["oatmeal", "warm taupe", "camel", "cocoa"],
    accents: ["clay rose", "moss", "terracotta", "muted teal"],
    avoid: ["icy blue", "fuchsia", "true black", "optic white"],
  },
  {
    key: "warm-autumn",
    season: "Warm Autumn",
    family: "autumn",
    temperature: "warm",
    value: "medium to deep",
    chroma: "rich / earthy",
    contrast: "medium",
    mood: "spiced, golden, grounded",
    appBackground: "#EBD9C0",
    appInk: "#3F2B20",
    palette: [
      { name: "Mustard", hex: "#C99B2E", use: "accent knits" },
      { name: "Rust", hex: "#B35F2E", use: "statement pieces" },
      { name: "Olive", hex: "#6F793D", use: "jackets and pants" },
      { name: "Copper", hex: "#A7663F", use: "makeup warmth" },
      { name: "Chocolate", hex: "#5A3728", use: "deep neutral" },
    ],
    neutrals: ["camel", "olive", "chocolate", "warm cream"],
    accents: ["rust", "mustard", "copper", "deep teal"],
    avoid: ["icy pink", "cool gray", "blue-red", "silver white"],
  },
  {
    key: "deep-autumn",
    season: "Deep Autumn",
    family: "autumn",
    temperature: "warm-neutral",
    value: "deep",
    chroma: "rich",
    contrast: "medium to high",
    mood: "espresso, forest, dark spice",
    appBackground: "#E5D4C2",
    appInk: "#2E251F",
    palette: [
      { name: "Espresso", hex: "#3B2A24", use: "tailoring" },
      { name: "Forest Olive", hex: "#4F5A35", use: "outerwear" },
      { name: "Auburn", hex: "#7F3F2F", use: "lip and accent" },
      { name: "Deep Teal", hex: "#1F5B58", use: "statement color" },
      { name: "Antique Gold", hex: "#A77B38", use: "metal and trim" },
    ],
    neutrals: ["espresso", "dark olive", "warm charcoal", "camel"],
    accents: ["auburn", "deep teal", "antique gold", "brick"],
    avoid: ["pastel lavender", "icy white", "bubblegum pink", "cool silver gray"],
  },
  {
    key: "bright-winter",
    season: "Bright Winter",
    family: "winter",
    temperature: "cool-neutral",
    value: "medium to deep",
    chroma: "bright / clear",
    contrast: "high",
    mood: "crisp, glossy, electric",
    appBackground: "#ECECEF",
    appInk: "#161B22",
    palette: [
      { name: "Icy Pink", hex: "#F4CFE1", use: "cool highlight" },
      { name: "Clear Fuchsia", hex: "#D61E72", use: "statement color" },
      { name: "Cobalt", hex: "#2457A6", use: "bold tops" },
      { name: "Emerald", hex: "#008A65", use: "clean accents" },
      { name: "Black", hex: "#111111", use: "sharp contrast" },
    ],
    neutrals: ["black", "optic white", "clear navy", "ice gray"],
    accents: ["fuchsia", "cobalt", "emerald", "icy pink"],
    avoid: ["mustard", "camel", "dusty rose", "muted olive"],
  },
  {
    key: "cool-winter",
    season: "Cool Winter",
    family: "winter",
    temperature: "cool",
    value: "medium to deep",
    chroma: "clear",
    contrast: "high",
    mood: "blue-red, jewel, precise",
    appBackground: "#EAEBEE",
    appInk: "#161A22",
    palette: [
      { name: "Blue Red", hex: "#C3213A", use: "lip and statement" },
      { name: "Royal Blue", hex: "#234E9B", use: "tops and dresses" },
      { name: "Pine", hex: "#0C5149", use: "deep accents" },
      { name: "Plum", hex: "#5B315D", use: "makeup depth" },
      { name: "Pure White", hex: "#F8F8F4", use: "crisp base" },
    ],
    neutrals: ["black", "pure white", "charcoal", "navy"],
    accents: ["blue red", "royal blue", "pine", "plum"],
    avoid: ["orange", "warm beige", "gold", "muddy brown"],
  },
  {
    key: "deep-winter",
    season: "Deep Winter",
    family: "winter",
    temperature: "cool-neutral",
    value: "deep",
    chroma: "clear to rich",
    contrast: "high",
    mood: "ink, berry, mineral depth",
    appBackground: "#E8E5E1",
    appInk: "#1E2024",
    palette: [
      { name: "Ink", hex: "#171A1F", use: "tailoring" },
      { name: "Black Cherry", hex: "#5A1F33", use: "lips and accents" },
      { name: "Deep Pine", hex: "#163B38", use: "outerwear" },
      { name: "Cool Espresso", hex: "#322A2A", use: "soft black alternative" },
      { name: "Mineral Ivory", hex: "#E7E1DA", use: "contrast base" },
    ],
    neutrals: ["ink", "cool espresso", "charcoal", "mineral ivory"],
    accents: ["black cherry", "deep pine", "burgundy", "sapphire"],
    avoid: ["camel", "orange rust", "dusty beige", "warm mustard"],
  },
];

const seasonAliases = new Map<string, string>([
  ["spring warm", "Warm Spring"],
  ["true spring", "Warm Spring"],
  ["warm spring", "Warm Spring"],
  ["light spring", "Light Spring"],
  ["bright spring", "Bright Spring"],
  ["summer cool", "Cool Summer"],
  ["true summer", "Cool Summer"],
  ["cool summer", "Cool Summer"],
  ["light summer", "Light Summer"],
  ["soft summer", "Soft Summer"],
  ["autumn warm", "Warm Autumn"],
  ["true autumn", "Warm Autumn"],
  ["warm autumn", "Warm Autumn"],
  ["soft autumn", "Soft Autumn"],
  ["deep autumn", "Deep Autumn"],
  ["dark autumn", "Deep Autumn"],
  ["winter cool", "Cool Winter"],
  ["true winter", "Cool Winter"],
  ["cool winter", "Cool Winter"],
  ["bright winter", "Bright Winter"],
  ["deep winter", "Deep Winter"],
  ["dark winter", "Deep Winter"],
]);

export function getSeasonPreset(season: string) {
  const normalized = season.trim().toLowerCase();
  const alias = seasonAliases.get(normalized);

  return (
    seasonPresets.find(
      (preset) =>
        preset.season === alias ||
        preset.season.toLowerCase() === normalized ||
        normalized.includes(preset.season.toLowerCase()),
    ) ?? seasonPresets[5]
  );
}
